---

- name: Install RPM requirements
  ansible.builtin.dnf:
    name:
      - python3-cryptography
      - openssl
    state: present
  tags: ["install"]

- name: Generate private key
  community.crypto.openssl_privatekey:
    path: "{{ nextcloud_ssl_private_key }}"
    size: 4096
    owner: "root"
    group: "root"
    mode: "0600"
    return_content: true  # Check mode compatibility on re-runs
  register: __nc_ssl_pk
  notify: Restart apache

- name: Generate CSR
  # Don't need to see this
  diff: false
  check_mode: false
  # It will always change, since it's stored in memory
  changed_when: false
  community.crypto.openssl_csr_pipe:
    privatekey_content: "{{ __nc_ssl_pk.privatekey }}"
    common_name: "{{ nextcloud_certificate_cn }}"
    subject_alt_name: "{{ nextcloud_certificate_alt_name }}"
  register: __nc_ssl_csr

- name: Sign CSR
  community.crypto.x509_certificate:
    path: "{{ nextcloud_ssl_certificate }}"
    csr_content: "{{ __nc_ssl_csr.csr }}"
    privatekey_path: "{{ nextcloud_ssl_private_key }}"
    provider: selfsigned
    owner: "root"
    group: "root"
    mode: "0640"
  notify: Restart apache
