---

- name: Enable and start redis
  ansible.builtin.systemd:
    name: redis
    state: started
    enabled: true

- name: Restart apache
  ansible.builtin.systemd:
    name: httpd
    state: restarted

- name: Restart php-fpm
  ansible.builtin.systemd:
    name: php-fpm
    state: restarted

- name: Enable and start nextcloud cron timer
  ansible.builtin.systemd:
    name: nextcloud-cron.timer
    state: started
    enabled: true
    daemon_reload: true
